document.write("<table width=\"815\" height=\"184\">");
document.write("<tbody>");
document.write("<tr>");
document.write("<td> <img src=\"files\/imgs\/sam_behseta.jpeg\" alt=\"Sam Behseta\"");
document.write("width=\"161\" height=\"200\"> <\/td>");
document.write("<td>");
document.write("<h1>Sam Behseta <\/h1>");
document.write("<h2>Professor of Statistics and Data Science<\/h2>");
document.write("<h2><a href=\"https:\/\/fullerton.edu\">CSUF<\/a><\/h2>");
document.write("<br>");
document.write("Address: Department of Mathematics, California State University Fullerton, CA, 92831 <br>");
document.write("E-mail: sbehseta@fullerton.edu <br>");
document.write("<br>");
document.write("&nbsp;");
document.write("<a href=\"https:\/\/www.linkedin.com\/in\/sam-behseta-35a71185\/\"> <img src=\"files\/imgs\/linkedin.png\" alt=\"Linked In\" width=\"25\" height=\"25\"><\/a> &nbsp;");
document.write("<a href=\"https:\/\/twitter.com\"> <img src=\"files\/imgs\/twitter.png\" alt=\"Twitter\"  border=\"0\" height=\"25\"><\/a><br>");
document.write("<\/td>");
document.write("<\/tr>");
document.write("<\/tbody>");
document.write("<\/table>");
